services:
  postgres:
    image: postgres:15
    container_name: medusa-postgres
    environment:
      POSTGRES_DB: medusa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medusa-network

  redis:
    image: redis:7-alpine
    container_name: medusa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - medusa-network

volumes:
  postgres_data:
  redis_data:

networks:
  medusa-network:
    driver: bridge 